version: '3'
services:
  uwu-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: on-failure
    networks:
      - uwu-network
    volumes:
      - uwu-redis-volume:/tmp

  uwu-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: on-failure
    ports:
      - "10001:80"
    networks:
      - uwu-network
    volumes:
      - uwu-redis-volume:/tmp

  uwu-redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    restart: on-failure
    networks:
      - uwu-network
    volumes:
      - uwu-redis-volume:/tmp

networks:
  uwu-network:
    driver: bridge

volumes:
  uwu-redis-volume:
